title: Rijk van Zanten
email: vanzr998@newschool.edu
description: >-
  My assignments for the classes MPS CS at Parsons!
baseurl: "/"
url: "https://rijkvanzanten.github.io"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
collections:
  pages:
    output: true
    permalink: /:path
highlighter: rouge
